### PR TITLE
Install all headers for pdf2htmlEX

### PR DESCRIPTION
**Pull request by andiwand**

### CODE REVIEW

**Comment by ViliusSutkus89** [comment]
I'm not really sure what's the reason for this. I don't mind it, it's just that I don't see a reason for it. pdf2htmlEX library is used through the `pdf2htmlEX class`, which is declared in `pdf2htmlEX.h`. That header file is marked in CMake as `PUBLIC_HEADER` and installed through CMake install. All the other headers are internal use. So I'm not really seeing the reason

**Comment by andiwand** [comment]
I am in the process of detangling the patched pdf2htmlEX files and just use vanilla. That requires getting access to all the headers

**Comment by ViliusSutkus89** [comment]
but vanilla pdf2htmlEX has no library, only the binary executable

**Comment by andiwand** [comment]
Right I think that is the only patch we need. We do not need to touch the code

**Comment by andiwand** [comment]
https://github.com/opendocument-app/OpenDocument.core/pull/387 I haven't followed up with this in a while but want to come back to it

**Comment by ViliusSutkus89** [comment]
Agree on the 387, but https://github.com/opendocument-app/conan-odr-index/issues/9 is more problematic right now.

As for the library code, I think current patches here are missing the pdf2htmlEX class. ( https://github.com/ViliusSutkus89/pdf2htmlEX/blob/library/pdf2htmlEX/src/pdf2htmlEX.h and https://github.com/ViliusSutkus89/pdf2htmlEX/blob/library/pdf2htmlEX/src/libpdf2htmlEX.cc ). That class is a recreation of main() function from https://github.com/opendocument-app/pdf2htmlEX/blob/odr/main/pdf2htmlEX/src/pdf2htmlEX.cc

**Comment by ViliusSutkus89** [comment]
387 depends on this, because `ERROR: Package 'pdf2htmlex/0.18.8.rc1-20240905-git' not resolved: Unable to find 'pdf2htmlex/0.18.8.rc1-20240905-git' in remotes`. I'll try to clean up the patches to have the library available

**Pull request merged**
